python 22.8.Project_Wheel_of_Python.py
#python 22.7.Assessment.py
#python 22.6.Exercises.py
#python 22.5.Tamagotchi_revisited.py
#python 22.4.Invoking_Parent_class.py
#python 22.3.Overriding_Methods.py
#python 22.2.Inheriting_variables_methods.py
#python 22.1.Intro_Inheritance.py
#python 21.3.Code_One_Section_at_a_time.py
#python 21.1.Building_Program_Strategy.py
#python 20.16.Assessment.py
#python 20.15.Exercises.py
#python 20.13.Tamagotchi_game.py
#python 20.12.Testing_classes.py
#python 20.10.Class_var_instance_var.py
#python 20.9.Sorting_lists_Instances.py
#python 20.8.Instances_as_return.py
#python 20.7.Converting_object_to_string.py
#python 20.6.Objects_as_Arg_para.py
#python 20.5.Adding_other_methods.py
#python 20.4.Adding_Param_to_Constructor.py
#python 20.3.User_Defined_classes.py
#python 20.1.Intro_classes_objects.py
#python 19.5.Exercises.py
#python 19.3.When_to_use_try_except.py
#python 19.1.What_s_exception.py
#python 18.8.Program_Develpment.py
#python 18.6.Writing_test_cases_for_fnt.py
#python 18.5.Testing_loops.py
#python 18.2.Checking_Assump_data.py
#python 18.1.Intro_test_cases.py
#python 17.8.Exercises.py
#python 17.7.Extracting_frm_Nested_data.py
#python 17.6.Deep_Shallow_copies.py
#python 17.5.Structuring_Nested_Data.py
#python 17.4.Nested_iteration.py
#python 17.3.Processing_JSON_results.py
#python 17.2.Nested_dict.py
#python 17.1.Intro_Nested_dat_iter.py
#python 16.10.Project_Sentiment.py
#python 16.8.Exercises.py
#python 16.6.When_use_Lambda.py
#python 16.5.Breaking_ties_2nd_sorting.py
#python 16.4.Sorting_Dict.py
#python 16.3.Optional_key_parameter.py
#python 16.2.Optional_reverse_parameter.py
#python 16.1.Intro_Sorting_w_Sort_Sorted.py
#python 15.6.Exercise.py
#python 15.3.Anonymous_fnct_with_lambda.py
#python 15.2.Keyword_para.py
#python 15.1.Intro_optional_para.py
#python 12.16.Exercises.py
#python 12.13.Passing_mutable_objects.py
#python 12.10.Fnct_call_fnct.py
#python 12.9.Global_variables.py
#python 12.7.Fnction_tht_accumulates.py
#python 12.5.Returning_val_frm_fction.py
#python 12.3.Fnct_Invocation.py
#python 12.1.Intro_to_fnt.py
#python 11.11.Exercises.py
#python 11.8.Accum_the_best_key.py
#python  11.7.Accumulating_results_from_dic.py
#python 11.6.Intro_Accumtg_mul_rslts_in_dic.py
#python 11.5.Aliasing_and_copying.py
#python 11.4.Dictionary_methods.py
#python 11.3.Dictionary_Operations.py
#python 11.2.Getting_Started_with_Dictionaries.py
#python 10.14.Exercises.py
#python 10.11.Writing_data_to_CSV_file.py
#python 10.10.Reading_data_from_csv_file.py
#python 10.9.CSV_format.py
#python 10.8.Writing_text_files.py
#python 10.6.Using_with_for_files.py
#python 10.5.Finding_a_file_in_your_Filesystem.py
#python 10.4.Iterating_over_lines_in_a_file.py
#python 10.2.Reading_a_file.py
#python 9.15.Exercises.py
#python 9.13.Dont_Mutate_A_list_while_iterating.py
#python 9.11.Accumulator_Pattern_Strings.py
#python 9.10.Accumulator_Pattern_with_List.py
#python 9.9.Non_Mutating_Methods_on_strings.py
#python 9.8.Append_versus_Concatenate.py
#python 8.10.Accumulator_Pattern_conditional.py
#python 8.9.Chained_conditionals.py
#python 8.3.Logical_operators.py
#python 8.1.Intro_to_conditional.py
#python 7.14.Exercises.py
#python 7.8.Nested_Iteration_ImgProcessing.py
#python 7.6.Accumulator_Pattern.py
#python 7.4.Strings_for_loop.py
#python 6.9.Splitting_Joining_strings.py
#python 5.12.Assessment.py
#python 5.8.Incremental_pragamming.py
#python 5.5.Repetition_with_forLoop.py
#python 5.3.Instances.py
#python 5.2.First_turtle.py
#python 5.1.turtle_lesson.py
#python 4.Module.py
